[theme]
base = "light"
primaryColor = "#79C1E4"
backgroundColor = "#F1F5FA"
secondaryBackgroundColor = "#F4F7FB"
textColor = "#30343B"
font = "sans serif"
baseFontSize = 16
dataframeHeaderBackgroundColor = "#E8F0F7"

[server]
headless = true
maxUploadSize = 5

[browser]
gatherUsageStats = false
